services:
  frontend_prod:
    build:
      context: .
      dockerfile: Dockerfile # match Dockerfile name
      target: production # use production stage
      args:
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH:?NEXT_PUBLIC_BASE_PATH is required}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:?NEXT_PUBLIC_API_BASE_URL is required}
        BUILD_DATABASE_URL: postgresql://build:build@localhost:5432/build
    container_name: keshav_frontend
    restart: always
    env_file:
      - path: ${APP_ENV_FILE:-.env.production}
        required: true
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

  nginx:
    depends_on:
      - frontend_prod
