services:
  frontend_prod:
    build:
      context: .
      dockerfile: Dockerfile # match Dockerfile name
      target: production # use production stage
    container_name: keshav_frontend
    restart: always
    env_file:
      - .env.production
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - app-net

  nginx:
    depends_on:
      - frontend_prod
